"""added_academic level

Revision ID: db52eeaa9216
Revises: 
Create Date: 2025-11-03 23:22:43.776854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db52eeaa9216'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('academic_level', sa.Enum('COLLEGE', 'UNIVERSITY', 'MASTERS', 'PROFESSOR', name='academiclevel'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'academic_level')
    # ### end Alembic commands ###
